replicas: 3
image:
  name: infra-demo-app
  tag: traced2
service:
  port: 8080
  nodePort: 30080
config:
  APP_NAME: infra-demo-k8s
env:
  OTEL_SERVICE_NAME: demo-app
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
ingress:
  enabled: true
  className: nginx
  host: demo.local
