replicas: 3
image:
  name: ghcr.io/mels-010101/infra-demo-app
  tag: "8d4910c6a79eeae6cf97bacff6aa1fd446e7179f"
service:
  port: 8080
  nodePort: 30080
config:
  APP_NAME: infra-demo-CANARY-V2
env:
  OTEL_SERVICE_NAME: demo-app
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
ingress:
  enabled: false
  className: nginx
  host: demo.local
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
rollout:
  enabled: true
