---
node_exporter_version: "1.9.1"
node_exporter_port: "9100"
prometheus_port: "9090"
grafana_port: "3000"
# Если в vault задать vault_grafana_admin_password — возьмётся оттуда
grafana_admin_password: "{{ vault_grafana_admin_password | default('admin') }}"
grafana_version: "10.4.7"
