apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"monitoring.coreos.com/v1\",\"kind\":\"PrometheusRule\",\"metadata\":{\"annotations\":{},\"labels\":{\"release\":\"kube-prometheus-stack\"},\"name\":\"demo-app-slo\",\"namespace\":\"monitoring\"},\"spec\":{\"groups\":[{\"name\":\"demo-app.slo\",\"rules\":[{\"alert\":\"HighErrorRate\",\"annotations\":{\"description\":\"5xx
      ошибок больше 1% уже 2 минуты. Текущее значение: {{ $value | humanizePercentage
      }}\",\"summary\":\"\U0001F6A8 Высокий error rate в demo-app\"},\"expr\":\"(\\n
      \ sum(rate(http_requests_total{job=\\\"demo-app\\\", status=~\\\"5..\\\"}[5m]))\\n
      \ /\\n  sum(rate(http_requests_total{job=\\\"demo-app\\\"}[5m]))\\n) \\u003e
      0.01\\n\",\"for\":\"2m\",\"labels\":{\"severity\":\"critical\"}},{\"alert\":\"SLOBreach\",\"annotations\":{\"description\":\"Доступность
      за последний час ниже 99%. Текущее значение: {{ $value | humanize }}%\",\"summary\":\"\U0001F494
      SLO пробит в demo-app\"},\"expr\":\"(\\n  sum(rate(http_requests_total{job=\\\"demo-app\\\",
      status!~\\\"5..\\\"}[1h]))\\n  /\\n  sum(rate(http_requests_total{job=\\\"demo-app\\\"}[1h]))\\n)
      * 100 \\u003c 99\\n\",\"for\":\"5m\",\"labels\":{\"severity\":\"critical\"}},{\"alert\":\"TargetDown\",\"annotations\":{\"description\":\"Prometheus
      не видит ни одной живой цели demo-app уже больше минуты.\",\"summary\":\"⚠️
      demo-app полностью недоступен\"},\"expr\":\"absent(up{job=\\\"demo-app\\\"})\",\"for\":\"1m\",\"labels\":{\"severity\":\"warning\"}}]}]}}\n"
  creationTimestamp: "2026-09-15T11:02:00Z"
  generation: 3
  labels:
    release: kube-prometheus-stack
  name: demo-app-slo
  namespace: monitoring
  resourceVersion: "75960"
  uid: 14fd8b89-fc20-4450-9259-b41fb333e4ec
spec:
  groups:
  - name: demo-app.slo
    rules:
    - alert: HighErrorRate
      annotations:
        description: '5xx ошибок больше 1% уже 2 минуты. Текущее значение: {{ $value
          | humanizePercentage }}'
        summary: "\U0001F6A8 Высокий error rate в demo-app"
      expr: |
        (
          sum(rate(http_requests_total{job="demo-app", status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="demo-app"}[5m]))
        ) > 0.01
      for: 2m
      labels:
        severity: critical
    - alert: SLOBreach
      annotations:
        description: 'Доступность за последний час ниже 99%. Текущее значение: {{
          $value | humanize }}%'
        summary: "\U0001F494 SLO пробит в demo-app"
      expr: |
        (
          sum(rate(http_requests_total{job="demo-app", status!~"5.."}[1h]))
          /
          sum(rate(http_requests_total{job="demo-app"}[1h]))
        ) * 100 < 99
      for: 5m
      labels:
        severity: critical
    - alert: TargetDown
      annotations:
        description: Prometheus не видит ни одной живой цели demo-app уже больше минуты.
        summary: ⚠️ demo-app полностью недоступен
      expr: absent(up{job="demo-app"})
      for: 10s
      labels:
        severity: warning
