---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-credentials
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCpf49u2fgKgcb0GX9ZyaRBg7Y03vt1ROphUt3ykE6jWobFa253EcG3H84Lkvn2ZTHly//c85JVgwvdLvBIVMmFNVtKyY5DORsjEQBe6G8S5G9BSSH5WjYib1JDYayUyrYrDS9KfWYwr3XfZt7UfE7kGSN1w0arToyB8gTx45NEoHbfi4tqeKiY0MlQGcrLLVkFeKh5b1erj2l3OsD7ZRep4e1Wh9vRGEeCb7PQVDAa8CCaC3/tOuFPKZGwTL/00337MqIiOf/9cwkHGdo+P+JTZgBY4jeJST/IJf2Hl/qKYx1pTIUopsb9zTTGgWHBhNLdnqiMrzGM0PW8MBDAzzgS/23NrWek8CDvfwf1bRvg+4Cdk+b6oXLwRGfTmX12BNtA06IsOIOnrpTRl3STELLtfEY8eGe4SYnFST4BcPAD8KK4kUr2BsAIEzFLAp7ECvjWH2fC/6D6TINxgtydrFuw6py+z0uYrZjm+RfSe477qdRKHtCHiIevGcWu6SlysmoRAnhc+0nrfxUSeGe/hficS3Z0zz+rJHFFhHZSiSk0N3g84Fc+1gMov0LQyekZfSMR/bbEFW7ZbcpNLSTPyxHkh4eIhXkC+aEv/1JRrNZlZ542F7DNY2OZpiuwPRRW3tVsBk0Dnt9EYIszFsEtwd2gUDxZj4R3Dikc0ucwNH2s3wcMCxExUhWEeN+F/iw+x9+5Zqw/VwSWrmpMVGRZf3N7gk5hOLNrmgzXMztkcWr8SdCfqsVMpqAtwzONWRhE
  template:
    metadata:
      creationTimestamp: null
      name: telegram-credentials
      namespace: monitoring
    type: Opaque
