apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: demo-app:monitoring.coreos.com/ServiceMonitor:default/demo-app
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"demo-app:monitoring.coreos.com/ServiceMonitor:default/demo-app"},"labels":{"app":"demo-app","release":"monitoring"},"name":"demo-app","namespace":"default"},"spec":{"endpoints":[{"interval":"15s","path":"/metrics","port":"http","relabelings":[{"replacement":"demo-app","sourceLabels":["__meta_kubernetes_service_label_app"],"targetLabel":"job"}]}],"selector":{"matchLabels":{"app":"demo-app"}}}}
  labels:
    app: demo-app
    release: monitoring
  name: demo-app
  namespace: default
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
    relabelings:
    - action: replace
      replacement: demo-app
      sourceLabels:
      - __meta_kubernetes_service_label_app
      targetLabel: job
  jobLabel: app
  selector:
    matchLabels:
      app: demo-app
