apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  project: default
  source:
    repoURL: https://github.com/MELS-010101/infra-ansible.git
    targetRevision: main
    path: charts/demo-app
    helm:
      releaseName: demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
